services:
  #dev service
  app:
    container_name: ride-sharing
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      # - /app/node_modules
    depends_on:
      - db

  # database services:
  db:
    image: postgres:18-alpine
    container_name: ride-sharing-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis
    environment:
      REDIS_PORT: 6380
      REDIS_HOST: localhost

    ports:
      - '6380:6379'

volumes:
  db-data:
