services:
  #dev service
  app-dev:
    container_name: ride-sharing-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      # - /app/node_modules
    depends_on:
      - db
    profiles:
      - dev

  #production service
  app-prod:
    container_name: ride-sharing-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    ports:
      - '8080:3000'
    depends_on:
      - db
    profiles:
      - prod

  # database services:
  db:
    image: postgres:18-alpine
    container_name: ride-sharing--db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  
  redis:
    image: redis
    environment:
      REDIS_PORT: 6380
      REDIS_HOST: localhost

    ports:
      - '6380:6379'


volumes:
  db-data:
